'use client'

import { useRef } from 'react'
import type { Outcome } from '@/lib/types'

export interface PredictionReportProps {
  studentId: string
  prediction: Outcome
  confidence: number
  probabilities: {
    Dropout: number
    Graduate: number
    Enrolled: number
  }
  inputSummary: Record<string, number>
  topFeatures: Array<{
    feature: string
    shap_value: number
    direction: 'up' | 'down'
    explanation: string
  }>
}

export function PredictionReport({
  studentId,
  prediction,
  confidence,
  probabilities,
  inputSummary,
  topFeatures,
}: PredictionReportProps) {
  const reportRef = useRef<HTMLDivElement>(null)

  const handleExportPDF = () => {
    window.print()
  }

  const getPredictionColor = (pred: Outcome): string => {
    switch (pred) {
      case 'Dropout':
        return 'bg-red-600'
      case 'Graduate':
        return 'bg-green-600'
      case 'Enrolled':
        return 'bg-blue-600'
    }
  }

  const getPredictionBGColor = (pred: Outcome): string => {
    switch (pred) {
      case 'Dropout':
        return 'bg-red-50 border-red-200'
      case 'Graduate':
        return 'bg-green-50 border-green-200'
      case 'Enrolled':
        return 'bg-blue-50 border-blue-200'
    }
  }

  const getPredictionTextColor = (pred: Outcome): string => {
    switch (pred) {
      case 'Dropout':
        return 'text-red-900'
      case 'Graduate':
        return 'text-green-900'
      case 'Enrolled':
        return 'text-blue-900'
    }
  }

  const getRecommendation = (pred: Outcome): { title: string; items: string[] } => {
    switch (pred) {
      case 'Dropout':
        return {
          title: 'High Priority Interventions',
          items: [
            'Schedule immediate academic advising session',
            'Connect student with peer mentoring programs',
            'Explore financial assistance options',
            'Provide resources for course selection and study skills',
            'Monitor grades closely in remaining semesters',
          ],
        }
      case 'Graduate':
        return {
          title: 'Support for Success',
          items: [
            'Encourage participation in research opportunities',
            'Suggest advanced coursework and seminars',
            'Provide guidance for postgraduate planning',
            'Connect with alumni network and career services',
            'Continue current academic support as needed',
          ],
        }
      case 'Enrolled':
        return {
          title: 'Engagement and Retention',
          items: [
            'Maintain regular check-ins with academic advisor',
            'Encourage involvement in student organizations',
            'Monitor course completion and progress',
            'Provide support for course selection',
            'Identify any emerging challenges early',
          ],
        }
    }
  }

  const recommendation = getRecommendation(prediction)
  const nonZeroInputs = Object.entries(inputSummary).filter(([, value]) => value !== 0)

  return (
    <>
      {/* Screen View */}
      <div className="space-y-6 print:hidden">
        <button
          onClick={handleExportPDF}
          className="px-6 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 transition-colors"
        >
          Export PDF Report
        </button>
      </div>

      {/* Print View */}
      <div
        ref={reportRef}
        className="hidden print:block p-8 bg-white text-black font-serif text-sm leading-relaxed"
      >
        {/* Header */}
        <div className="border-b border-black pb-6 mb-6">
          <h1 className="text-2xl font-bold mb-2">Student Retention Risk Assessment Report</h1>
          <p className="text-xs">
            Date: {new Date().toLocaleDateString()} | Generated by: Student Retention Predictor
          </p>
        </div>

        {/* Student ID */}
        <div className="mb-6">
          <p className="text-xs font-bold">Student ID: {studentId}</p>
        </div>

        {/* Input Summary */}
        {nonZeroInputs.length > 0 && (
          <div className="mb-6">
            <h2 className="text-lg font-bold mb-3">Input Summary</h2>
            <table className="w-full border border-black text-xs">
              <tbody>
                {nonZeroInputs.map(([key, value]) => (
                  <tr key={key} className="border-b border-black">
                    <td className="p-2 font-bold border-r border-black w-1/2">
                      {key.replace(/_/g, ' ').toUpperCase()}
                    </td>
                    <td className="p-2 text-right">{typeof value === 'number' ? value.toFixed(2) : value}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* Prediction Result */}
        <div className="mb-6 p-4 border-2 border-black">
          <h2 className="text-lg font-bold mb-3">Prediction Result</h2>
          <div className="flex items-center gap-4">
            <div className={`px-6 py-4 ${getPredictionColor(prediction)} text-white text-center font-bold`}>
              <div className="text-xl">{prediction.toUpperCase()}</div>
              <div className="text-sm mt-1">{(confidence * 100).toFixed(1)}% Confidence</div>
            </div>
          </div>
        </div>

        {/* Probability Breakdown */}
        <div className="mb-6">
          <h2 className="text-lg font-bold mb-3">Probability Breakdown</h2>
          <div className="space-y-2">
            {Object.entries(probabilities).map(([outcome, prob]) => (
              <div key={outcome} className="flex items-center gap-3">
                <div className="w-20 text-xs font-bold">{outcome}</div>
                <div className="flex-1 bg-gray-200 border border-black h-6">
                  <div
                    className={`h-full ${
                      outcome === 'Dropout'
                        ? 'bg-red-600'
                        : outcome === 'Graduate'
                          ? 'bg-green-600'
                          : 'bg-blue-600'
                    }`}
                    style={{ width: `${prob * 100}%` }}
                  />
                </div>
                <div className="w-16 text-right text-xs font-bold">{(prob * 100).toFixed(1)}%</div>
              </div>
            ))}
          </div>
        </div>

        {/* Top Features */}
        <div className="mb-6">
          <h2 className="text-lg font-bold mb-3">Top 5 Most Influential Features</h2>
          <ol className="list-decimal list-inside space-y-2 text-xs">
            {topFeatures.slice(0, 5).map((feature, idx) => (
              <li key={idx} className="ml-2">
                <strong>{feature.feature}</strong> - {feature.explanation}
              </li>
            ))}
          </ol>
        </div>

        {/* Recommendations */}
        <div className="mb-6 p-4 border border-black">
          <h2 className="text-lg font-bold mb-3">{recommendation.title}</h2>
          <ul className="list-disc list-inside space-y-1 text-xs">
            {recommendation.items.map((item, idx) => (
              <li key={idx} className="ml-2">
                {item}
              </li>
            ))}
          </ul>
        </div>

        {/* Footer */}
        <div className="border-t border-black pt-4 mt-8 text-xs">
          <p className="font-bold">
            Model: XGBoost | Reference: Ridwan et al. (2024) | Dataset: Higher Education Predictors of
            Student Retention
          </p>
        </div>
      </div>
    </>
  )
}
